apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: digital-backbone-adapter-api
  description: APIs for the Howden Digital Backbone integration platform
spec:
  type: openapi
  lifecycle: production
  owner: group:default/platform-team
  definition: |
    openapi: 3.0.3
    info:
      title: Digital Backbone Adapter API
      version: 1.0.0
    servers:
      - url: https://api.dbb.howdengrp.com
    paths: {}