apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: digital-backbone-adapter-api
  title: Digital Backbone Adapter API
  description: APIs for the Howden Digital Backbone integration platform
spec:
  type: openapi
  lifecycle: production
  owner: user:guest
  definition:
    $file: ../../catalog/apis/digital-backbone-api-entity.yaml